services:
  mysql:
    # ACHTUNG
    # The image is heavily bugged !
    # MySQL 8.4 LTS was released on 30.04.2026.
    # Support till April 2032.
    image: mysql:8.4
    container_name: mysql
    restart: always
    command: --max-allowed-packet=64M
    ports:
      # A standard MySQL port is 3306.
      - '3306:3306'
    volumes:
      - type: bind
        # Path to the local (host) data folder.
        source: mysql_data
        target: /var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=xxx'
